// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MyHomeWebsite.Data;
using System;

namespace MyHomeWebsite.Migrations
{
    [DbContext(typeof(MyWebsiteDbContext))]
    [Migration("20180729203906_fifthIntialCreate")]
    partial class fifthIntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyHomeWebsite.Models.TimePeriod", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("End_Time");

                    b.Property<DateTime>("Start_Time");

                    b.HasKey("ID");

                    b.ToTable("TimePeriod");
                });

            modelBuilder.Entity("MyHomeWebsite.Models.WorkExperience", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Responsibility");

                    b.Property<string>("SkillGained");

                    b.Property<string>("experience");

                    b.Property<Guid?>("timePeriodID");

                    b.HasKey("ID");

                    b.HasIndex("timePeriodID");

                    b.ToTable("workExperiences");
                });

            modelBuilder.Entity("MyHomeWebsite.Models.WorkExperience", b =>
                {
                    b.HasOne("MyHomeWebsite.Models.TimePeriod", "timePeriod")
                        .WithMany()
                        .HasForeignKey("timePeriodID");
                });
#pragma warning restore 612, 618
        }
    }
}
